[package]
name = "rpc_load_balancer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
<<<<<<< HEAD
log = "0.4"
env_logger = "0.9"
=======
pingora = { version = "0.4", features = ["lb"] }
actix-web = "4"
tokio = { version = "1.42.0", features = ["full"] }
>>>>>>> parent of 74b37fe (#2 fix; add health check background service)
